import type { APIRoute } from 'astro'
import { getCollection } from 'astro:content'
import config from '../../website.config'
import { docHref } from '../utils/docs-tree'
import { postHref } from '../utils/blog'

const siteUrl = config.site.replace(/\/$/, '')

/**
 * Serves /llms.txt, a plain-text index optimized for LLM crawlers: every page
 * of the site with a short description, pointing at the markdown twins
 * generated by the enrich-md integration.
 */
export const GET: APIRoute = async () => {
  const [docs, posts, pages] = await Promise.all([
    getCollection('docs'),
    getCollection('blog', (post) => !post.data.draft),
    getCollection('pages'),
  ])

  const lines: string[] = [
    `# ${config.siteName}`,
    '',
    config.description,
    '',
    `A markdown version of every page is available by appending \`.md\` to its URL (e.g. ${siteUrl}/docs/getting-started.md).`,
    '',
    '## Pages',
    '',
  ]

  for (const page of [...pages].sort((a, b) => a.id.localeCompare(b.id))) {
    const path = page.id === 'index' ? '/' : `/${page.id}`
    const suffix = page.data.description ? `: ${page.data.description}` : ''
    lines.push(`- [${page.data.title}](${siteUrl}${path})${suffix}`)
  }
  lines.push(`- [Blog](${siteUrl}/blog)`)

  lines.push('', '## Documentation', '')
  const byOrder = [...docs].sort(
    (a, b) => (a.data.order ?? 999) - (b.data.order ?? 999)
  )
  for (const doc of byOrder) {
    const suffix = doc.data.description ? `: ${doc.data.description}` : ''
    lines.push(`- [${doc.data.title}](${siteUrl}${docHref(doc.id)})${suffix}`)
  }

  lines.push('', '## Blog', '')
  const byDate = [...posts].sort(
    (a, b) => (b.data.date?.getTime() ?? 0) - (a.data.date?.getTime() ?? 0)
  )
  for (const post of byDate) {
    lines.push(
      `- [${post.data.title}](${siteUrl}${postHref(post.id)}): ${post.data.summary}`
    )
  }

  lines.push('')

  return new Response(lines.join('\n'), {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  })
}
