import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Client',
      items: [{ type: 'autogenerated', dirName: 'client' }],
    },
    {
      type: 'category',
      label: 'Server',
      items: [{ type: 'autogenerated', dirName: 'server' }],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
  ],
}

export default sidebars
